title:            "ariedoublelee | A girl from Kaohsiung, Taiwan."
url:              http://ariedoublelee.com
permalink:        pretty
google_analytics: UA-123
timezone:         Asia/Taipei
sass:
  sass_dir: assets
  style: :compressed
